#import "hearts_fire.typ": hearts_fire
#import "flame_dart.typ": flame_dart
#import "ignite.typ": ignite
#import "enchant_weapon.typ": enchant_weapon
#import "flame_barrier.typ": flame_barrier
#import "pyroclasm.typ": pyroclasm
#import "fiery_embrace.typ": fiery_embrace
#import "living_inferno.typ": living_inferno
#import "dragonform.typ": dragonform