#let conditions = (
  asleep: [*Asleep:* Becoming Incapacitated until their next two turns have passed, until damaged, or until an ally uses an action to wake them.],
  blinded: [*Blinded:* Can't see. Attacks against you have advantage, and your attacks have disadvantage.],
  bloodied: [*Bloodied:* At half HP or less.],
  charmed: [*Charmed:* Sees the charmer as an ally. Charmer has advantage on social interactions with you.],
  dazed: [*Dazed:* Heroes: lose 1 action; monsters: can perform one less action on their next turn.],
  dying: [*Dying:* At 0 HP. Taking damage while dying causes 2 Wounds, a crit causes 3 instead.],
  frightened: [*Frightened:* Disadvantage on rolls when source of fear is nearby; speed halved when moving closer to it.],
  grappled: [*Grappled:* Cannot move. Attacks against you have advantage.],
  restrained: [*Restrained:* Cannot move. Attacks against you have advantage.],
  hampered: [*Hampered:* Any creature with their actions or movement reduced (e.g., Dazed, Grappled, Prone, Difficult Terrain).],
  incapacitated: [*Incapacitated:* Can't do anything. Attacks against you have advantage, and melee attacks that hit, crit.],
  invisible: [*Invisible:* Cannot be seen. Your attacks have advantage, and attacks against you have disadvantage.],
  petrified: [*Petrified:* Incapacitated. You have all the benefits and drawbacks of being a rock! Immune to most damage except from large explosions, picks, or similar tools.],
  poisoned: [*Poisoned:* Disadvantage on rolls.],
  prone: [*Prone:* Movement costs twice as much, and disadvantage on attacks. Melee attacks against you have advantage; Ranged have disadvantage. Spend 3 spaces of your Speed to stand up.],
  riding: [*Riding:* You move with the creature you are riding. Any attacks that miss you, strike them.],
  slowed: [*Slowed:* Speed halved during your next turn.],
  taunted: [*Taunted:* Disadvantage on attacks except against the most recent taunter.],
  wounded: [*Wounded:* Has any Wounds (typically 6 Wounds and a hero is dead).],
  smoldering: [*Smoldering:* This condition does nothing on its own, though some spells and abilities have additional effects against Smoldering creatures.],
)